
security:
    encoders:
        amiguetes\PtuitBundle\Entity\Usuario: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
          entity:
              class: amiguetes\PtuitBundle\Entity\Usuario
              property: email

    firewalls:
        
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login
            security: false    
        
        registro:
            pattern:  ^/registro
            security: false  
        
        favicon:
            pattern:  ^/favicon.ico
            security: false    

        secured_area:
            pattern:    ^/
            form_login: 
                check_path: /seguridad/login_check
                login_path: /login              
                
            logout:
                path:   /logout
                target: /login
                
            remember_me:
                key:      PtuitBundle
                lifetime: 3600
                path:     /
                domain:   ~ # El valor predeterminado es el dominio actual de $_SERVER
  

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/ , roles: ROLE_USER }
        - { path: ^/seguridad/login_check , role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/logout , role: IS_AUTHENTICATED_ANONYMOUSLY }