<?php

namespace amiguetes\PtuitBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PerfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilRepository extends EntityRepository {

    public function findPerfilUsuario($id) {
        $dql = "SELECT  p , u 
            FROM PtuitBundle:Perfil p
            JOIN p.usuario u            
            WHERE p.usuario=:id";

        return $this->getEntityManager()
                        ->createQuery($dql)
                        ->setParameter("id", $id)
                        ->getResult(\Doctrine\ORM\Query::HYDRATE_OBJECT);
    }

}