<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class amiguetesPtuitBundleEntityPerfilProxy extends \amiguetes\PtuitBundle\Entity\Perfil implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function setUsuario($usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function setFechaNacimiento($fecha)
    {
        $this->__load();
        return parent::setFechaNacimiento($fecha);
    }

    public function getFechaNacimiento()
    {
        $this->__load();
        return parent::getFechaNacimiento();
    }

    public function setIntereses($intereses)
    {
        $this->__load();
        return parent::setIntereses($intereses);
    }

    public function getIntereses()
    {
        $this->__load();
        return parent::getIntereses();
    }

    public function setBiografia($biografia)
    {
        $this->__load();
        return parent::setBiografia($biografia);
    }

    public function getBiografia()
    {
        $this->__load();
        return parent::getBiografia();
    }

    public function setLocalizacion($localizacion)
    {
        $this->__load();
        return parent::setLocalizacion($localizacion);
    }

    public function getLocalizacion()
    {
        $this->__load();
        return parent::getLocalizacion();
    }

    public function setWeb($web)
    {
        $this->__load();
        return parent::setWeb($web);
    }

    public function getWeb()
    {
        $this->__load();
        return parent::getWeb();
    }

    public function setPrivacidad($privacidad)
    {
        $this->__load();
        return parent::setPrivacidad($privacidad);
    }

    public function getPrivacidad()
    {
        $this->__load();
        return parent::getPrivacidad();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'telefono', 'fechaNacimiento', 'intereses', 'biografia', 'localizacion', 'web', 'usuario', 'privacidad');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}