<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class amiguetesPtuitBundleEntityMensajeProxy extends \amiguetes\PtuitBundle\Entity\Mensaje implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setCreado($creado)
    {
        $this->__load();
        return parent::setCreado($creado);
    }

    public function getCreado()
    {
        $this->__load();
        return parent::getCreado();
    }

    public function setModificado($modificado)
    {
        $this->__load();
        return parent::setModificado($modificado);
    }

    public function getModificado()
    {
        $this->__load();
        return parent::getModificado();
    }

    public function setTexto($texto)
    {
        $this->__load();
        return parent::setTexto($texto);
    }

    public function getTexto()
    {
        $this->__load();
        return parent::getTexto();
    }

    public function addReplicadoPorUsuario(\amiguetes\PtuitBundle\Entity\Usuario $replicadoPorUsuario)
    {
        $this->__load();
        return parent::addReplicadoPorUsuario($replicadoPorUsuario);
    }

    public function deleteReplicadoPorUsuario(\amiguetes\PtuitBundle\Entity\Usuario $usuario)
    {
        $this->__load();
        return parent::deleteReplicadoPorUsuario($usuario);
    }

    public function getReplicadoPorUsuario()
    {
        $this->__load();
        return parent::getReplicadoPorUsuario();
    }

    public function addUsuarioDeFavoritos(\amiguetes\PtuitBundle\Entity\Usuario $usuario)
    {
        $this->__load();
        return parent::addUsuarioDeFavoritos($usuario);
    }

    public function deleteUsuarioDeFavoritos(\amiguetes\PtuitBundle\Entity\Usuario $usuario)
    {
        $this->__load();
        return parent::deleteUsuarioDeFavoritos($usuario);
    }

    public function getUsuarioDeFavoritos()
    {
        $this->__load();
        return parent::getUsuarioDeFavoritos();
    }

    public function addTagid(\amiguetes\PtuitBundle\Entity\Tag $tagid)
    {
        $this->__load();
        return parent::addTagid($tagid);
    }

    public function getTagid()
    {
        $this->__load();
        return parent::getTagid();
    }

    public function setUsuario(\amiguetes\PtuitBundle\Entity\Usuario $usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'creado', 'modificado', 'texto', 'replicadoPorUsuario', 'usuarioDeFavoritos', 'tagid', 'usuario');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}